In [28]:
#####---------------------------------------DATA PREPROCESSING----------------------------################

In [29]:
import pandas as pd

df = pd.read_excel("clean_sales_data.xlsx")
df.head(5)

,transaction_id,customer_number,transaction_month,product_id,product_name,unit_price,volume_units,sales_amount,promo_offer
0,6ae6b99d-9158-43f2-ac7e-52f17620fc40,75583263,2022-01,P021,Dettol Antiseptic 250ml,305.70,10,3057.00,Yes
1,6ae6b99d-9158-43f2-ac7e-52f17620fc40,75583263,2022-01,P026,Kellogg's Corn Flakes 500g,405.20,5,2026.00,Yes
2,6ae6b99d-9158-43f2-ac7e-52f17620fc40,75583263,2022-01,P009,Lays Chips 200g,322.60,10,3226.00,Yes
3,6ae6b99d-9158-43f2-ac7e-52f17620fc40,75583263,2022-01,P037,Vim Dishwash Bar 200g,176.27,9,1586.43,Yes
4,a1e86962-46d7-4940-8759-b58c535b370b,75583263,2022-01,P026,Kellogg's Corn Flakes 500g,477.55,10,4775.50,No

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82950 entries, 0 to 82949
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     82950 non-null  object
 1   customer_number    82950 non-null  int64
 2   transaction_month  82950 non-null  object
 3   product_id         82950 non-null  object
 4   product_name       82950 non-null  object
 5   unit_price         82950 non-null  float64
 6   volume_units       82950 non-null  int64
 7   sales_amount       82950 non-null  float64
 8   promo_offer        82950 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 5.7+ MB

In [31]:
df.describe()

       customer_number    unit_price  volume_units  sales_amount
count     8.295000e+04  82950.000000  82950.000000  82950.000000
mean      4.973458e+07    273.435430      5.497601   1503.266978
std       2.866339e+07    162.663667      2.873561   1280.993174
min       3.277000e+03     29.220000      1.000000     29.570000
25%       2.432787e+07    127.200000      3.000000    504.490000
50%       4.978368e+07    243.490000      5.000000   1095.100000
75%       7.489914e+07    378.760000      8.000000   2219.805000
max       9.996990e+07    582.850000     10.000000   5828.500000

In [32]:
df.isnull().sum()

transaction_id       0
customer_number      0
transaction_month    0
product_id           0
product_name         0
unit_price           0
volume_units         0
sales_amount         0
promo_offer          0
dtype: int64

In [33]:
df.drop_duplicates(inplace=True)

In [34]:
df["transaction_month"] = pd.to_datetime(df["transaction_month"], format="%Y-%m")

In [35]:
df["transaction_month"].head()

0   2022-01-01
1   2022-01-01
2   2022-01-01
3   2022-01-01
4   2022-01-01
Name: transaction_month, dtype: datetime64[ns]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82950 entries, 0 to 82949
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     82950 non-null  object
 1   customer_number    82950 non-null  int64
 2   transaction_month  82950 non-null  datetime64[ns]
 3   product_id         82950 non-null  object
 4   product_name       82950 non-null  object
 5   unit_price         82950 non-null  float64
 6   volume_units       82950 non-null  int64
 7   sales_amount       82950 non-null  float64
 8   promo_offer        82950 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 5.7+ MB

In [37]:
df["Year"] = df["transaction_month"].dt.year
df["Month"] = df["transaction_month"].dt.month
df["Month_Name"] = df["transaction_month"].dt.month_name()
df["Quarter"] = df["transaction_month"].dt.quarter

In [38]:
df["calculated_sales"] = df["unit_price"] * df["volume_units"]

difference = (df["calculated_sales"] - df["sales_amount"]).abs().sum()
print(difference)

4.607244363796781e-09

In [39]:
df["product_name"] = df["product_name"].str.strip().str.title()
df["promo_offer"] = df["promo_offer"].str.strip().str.lower()

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82950 entries, 0 to 82949
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     82950 non-null  object
 1   customer_number    82950 non-null  int64
 2   transaction_month  82950 non-null  datetime64[ns]
 3   product_id         82950 non-null  object
 4   product_name       82950 non-null  object
 5   unit_price         82950 non-null  float64
 6   volume_units       82950 non-null  int64
 7   sales_amount       82950 non-null  float64
 8   promo_offer        82950 non-null  object
 9   Year               82950 non-null  int32
 10  Month              82950 non-null  int32
 11  Month_Name         82950 non-null  object
 12  Quarter            82950 non-null  int32
 13  calculated_sales   82950 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(3), int64(2), object(5)
memory usage: 7.9+ MB

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82950 entries, 0 to 82949
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     82950 non-null  object
 1   customer_number    82950 non-null  int64
 2   transaction_month  82950 non-null  datetime64[ns]
 3   product_id         82950 non-null  object
 4   product_name       82950 non-null  object
 5   unit_price         82950 non-null  float64
 6   volume_units       82950 non-null  int64
 7   sales_amount       82950 non-null  float64
 8   promo_offer        82950 non-null  object
 9   Year               82950 non-null  int32
 10  Month              82950 non-null  int32
 11  Month_Name         82950 non-null  object
 12  Quarter            82950 non-null  int32
 13  calculated_sales   82950 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(3), int64(2), object(5)
memory usage: 7.9+ MB

In [42]:
df.to_csv("project_sales_data.csv", index=False)

In [43]:

import sqlite3

# Connect to database (creates file if not exists)
conn = sqlite3.connect("sales.db")

# Save dataframe as table
df.to_sql("sales_data", conn, if_exists="replace", index=False)

conn.close()

In [44]:
##########--------------------ANALYTICS AND CHATBOT BACKEND------------------------##################

In [47]:
from flask import Flask, render_template, request, jsonify, send_file
import sqlite3
import time
import csv
import os
import matplotlib.pyplot as plt
import google.generativeai as genai

In [46]:
app = Flask(__name__)
# Gemini API
genai.configure(api_key="AIzaSyAayXuw7-aNHGR3HtPWmWx8bphvRnuainc")
model = genai.GenerativeModel("gemini-2.5-flash")

chat_history = []

AttributeError: module 'google.genai' has no attribute 'configure'

In [ ]:
# SQL QUERY FUNCTION
# -----------------------------

def run_query(intent):

    conn = sqlite3.connect("sales.db")
    cursor = conn.cursor()

    if intent == "total_revenue":
        query = """
        SELECT SUM(sales_amount)
        FROM sales_data
        """

    elif intent == "yearly_sales":
        query = """
        SELECT strftime('%Y', order_date) AS year,
        SUM(sales_amount)
        FROM sales_data
        GROUP BY year
        """

    elif intent == "monthly_sales":
        query = """
        SELECT strftime('%m', order_date) AS month,
        SUM(sales_amount)
        FROM sales_data
        GROUP BY month
        """

    elif intent == "sales_by_region":
        query = """
        SELECT region,
        SUM(sales_amount)
        FROM sales_data
        GROUP BY region
        """

    elif intent == "category_sales":
        query = """
        SELECT product_category,
        SUM(sales_amount)
        FROM sales_data
        GROUP BY product_category
        """

    elif intent == "top_products":
        query = """
        SELECT product_name,
        SUM(sales_amount) AS total_sales
        FROM sales_data
        GROUP BY product_name
        ORDER BY total_sales DESC
        LIMIT 5
        """

    elif intent == "promo_sales":
        query = """
        SELECT promo_offer,
        SUM(sales_amount)
        FROM sales_data
        GROUP BY promo_offer
        """

    elif intent == "total_transactions":
        query = """
        SELECT COUNT(DISTINCT transaction_id)
        FROM sales_data
        """

    else:
        conn.close()
        return []

    cursor.execute(query)
    result = cursor.fetchall()

    conn.close()

    return result

In [ ]:
# CHART CREATION
# -----------------------------

def create_chart(intent, result):

    if not os.path.exists("static"):
        os.makedirs("static")

    if intent == "yearly_sales":

        years = [row[0] for row in result]
        sales = [row[1] for row in result]

        plt.figure()
        plt.bar(years, sales)
        plt.title("Yearly Sales")
        plt.xlabel("Year")
        plt.ylabel("Sales")

        chart_path = "static/yearly_sales.png"
        plt.savefig(chart_path)
        plt.close()

        return chart_path


    if intent == "category_sales":

        categories = [row[0] for row in result]
        sales = [row[1] for row in result]

        plt.figure()
        plt.pie(sales, labels=categories, autopct='%1.1f%%')
        plt.title("Category Sales")

        chart_path = "static/category_sales.png"
        plt.savefig(chart_path)
        plt.close()

        return chart_path

    return None

In [ ]:
# INTENT DETECTION
# -----------------------------

def detect_intent(question):

    prompt = f"""
    Identify the intent of the retail analytics question.

    Possible intents:
    total_revenue
    yearly_sales
    monthly_sales
    sales_by_region
    category_sales
    top_products
    promo_sales
    total_transactions

    Question: {question}

    Return ONLY the intent name from the list above.
    Do not explain anything.
    """

    try:
        response = model.generate_content(prompt)
        intent = response.text.strip().lower()
    except:
        intent = "total_revenue"

    return intent

In [ ]:
# HOME PAGE
# -----------------------------

@app.route("/")
def index():
    return render_template("index.html")

In [ ]:
# CHAT ROUTE
# -----------------------------

@app.route("/chat", methods=["POST"])
def chat():

    start = time.time()

    data = request.json
    question = data["message"]

    intent = detect_intent(question)

    result = run_query(intent)

    chart = create_chart(intent, result)

    prompt = f"""
    You are a retail analytics assistant.

    Explain the sales insight in ONLY 2 short lines.
    Use simple business language.
    Do NOT explain Python lists, tuples, or database structures.

    Data: {result}
    """

    try:
        response = model.generate_content(prompt)
        explanation = response.text
    except:
        explanation = "AI explanation temporarily unavailable due to API limit."

    processing_time = round(time.time() - start, 2)

    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

    chat_history.append({
        "question": question,
        "answer": explanation,
        "timestamp": timestamp,
        "processing_time": processing_time
    })

    return jsonify({
        "explanation": explanation,
        "processing_time": processing_time,
        "chart": chart,
        "history": chat_history
    })

In [ ]:
# DOWNLOAD REPORT
# -----------------------------

@app.route("/download")
def download_report():

    filename = "chat_report.csv"

    with open(filename, "w", newline="") as file:

        writer = csv.writer(file)

        writer.writerow([
            "Question",
            "Answer",
            "Timestamp",
            "Processing Time"
        ])

        for chat in chat_history:
            writer.writerow([
                chat["question"],
                chat["answer"],
                chat["timestamp"],
                chat["processing_time"]
            ])

    return send_file(filename, as_attachment=True)

In [ ]:
if __name__ == "__main__":
    app.run(debug=True)

In [ ]:
######--------------------CHATBOT UI-------------####################3

In [ ]:
from IPython.display import HTML

HTML("""
<!DOCTYPE html>
<html>
<head>

<title>Retail Sales Chatbot</title>

<style>

body{
font-family:Arial;
background:#f4f6f8;
margin:0;
}

.container{
display:flex;
height:100vh;
}

.left-panel{
width:25%;
background:#0c5db6;
padding:20px;
color:white;
}

.box{
background:#1a6ad6;
padding:15px;
margin-bottom:20px;
border-radius:5px;
}

.suggestion-btn{
display:block;
width:100%;
padding:8px;
margin:5px 0;
border:none;
background:white;
color:black;
cursor:pointer;
}

.right-panel{
width:75%;
padding:20px;
}

.chat-box{
background:white;
height:450px;
border:1px solid #ddd;
padding:15px;
overflow-y:auto;
}

.input-area{
margin-top:15px;
display:flex;
}

input{
flex:1;
padding:10px;
border:1px solid #ccc;
}

button{
padding:10px 20px;
margin-left:5px;
background:#0c5db6;
color:white;
border:none;
cursor:pointer;
}

</style>

</head>

<body>

<div class="container">

<div class="left-panel">

<div class="box">
<h3>Chat History</h3>
<div id="history"></div>
</div>

<div class="box">
<h3>Question Suggestions</h3>

<h3>Question Suggestions</h3>

<button class="suggestion-btn" onclick="sendSuggestion('Show total revenue')">Total Revenue</button>

<button class="suggestion-btn" onclick="sendSuggestion('Show yearly sales')">Yearly Sales</button>

<button class="suggestion-btn" onclick="sendSuggestion('Show monthly sales')">Monthly Sales</button>

<button class="suggestion-btn" onclick="sendSuggestion('Show sales by region')">Sales by Region</button>

<button class="suggestion-btn" onclick="sendSuggestion('Show product category sales')">Product Category Sales</button>

<button class="suggestion-btn" onclick="sendSuggestion('Show top products')">Top Products</button>

<button class="suggestion-btn" onclick="sendSuggestion('Show promo sales')">Promo Sales</button>

<button class="suggestion-btn" onclick="sendSuggestion('Show total transactions')">Total Transactions</button>
</div>

</div>


<div class="right-panel">

<h2>Chat Bot</h2>

<div class="chat-box" id="chatbox"></div>

<div class="input-area">

<input type="text" id="userInput" placeholder="Ask your question">

<button onclick="sendMessage()">Send</button>

</div>

<p id="processingTime">Query Processing Time:</p>

<button onclick="downloadReport()">Download Report</button>

</div>

</div>


<script>

function sendMessage(message=null){

let input=document.getElementById("userInput")
let question= message ? message : input.value

fetch("/chat",{

method:"POST",

headers:{
"Content-Type":"application/json"
},

body:JSON.stringify({
message:question
})

})
.then(res=>res.json())
.then(data=>{

let chat=document.getElementById("chatbox")

chat.innerHTML +=
"<p><b>Q:</b> "+question+"</p>" +
"<p><b>A:</b> "+data.explanation+"</p>"

if(data.chart){
chat.innerHTML += "<img src='"+data.chart+"' width='400'>"
}

chat.innerHTML += "<hr>"

document.getElementById("processingTime").innerText =
"Query Processing Time: "+data.processing_time+" sec"


let historyBox=document.getElementById("history")
historyBox.innerHTML=""

data.history.forEach(function(item){

historyBox.innerHTML +=
"<p>"+item.question+"</p>"

})

input.value=""

})

}


function sendSuggestion(q){

sendMessage(q)

}


function downloadReport(){

window.location="/download"

}

</script>

</body>
</html>
""")